# Disable default password, define admin user explicitly
#requirepass mysecret
aclfile /etc/redis/users.acl
#user default on >mysecret allcommands allkeys
# Define adapter1 with no permissions
#user adapter1 on >adapter1 ~* -@all
